<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bhargav" failures="1" tests="3" name="myTests" time="0.108" errors="0" timestamp="2023-09-29T20:14:39 IST">
  <testcase classname="QTT.Cyclos.ListenerDemo" name="test1" time="0.018"/>
  <testcase classname="QTT.Cyclos.ListenerDemo" name="test2" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at QTT.Cyclos.ListenerDemo.test2(ListenerDemo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="QTT.Cyclos.ListenerDemo" name="test3" time="0.0">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- myTests -->
